sudo: required

language: python

python:
  - "3.5"

services:
  - docker
  - mysql

before_install:
  - docker pull mysql
  - docker run --name mysqldb -d -p 3307:3306 -e MYSQL_ROOT_PASSWORD=password mysql
  - docker pull sath89/oracle-xe-11g
  - docker run --name orcldb -d -p 1521:1521 sath89/oracle-xe-11g
  - docker ps -a
  - docker exec -it orcldb "sqlplus"
  - docker exec -it orcldb "system"
  - docker exec -it orcldb "oracle"
  - docker exec -it orcldb "create user test quota unlimited on system identified by test;"
  - docker exec -it orcldb "create table test.table2 (id integer, column1 varchar2(100), column2 number);"
  - docker exec -it orcldb "exit"

install: "pip install -r requirements.txt"

script: nosetests

after_script:
  - docker rm -f mysqldb
  - docker rm -f orcldb