sudo: required

language: python

python:
  - "3.5"

services:
  - docker
  - mysql

before_install:
  - docker pull mysql
  - docker run --name mysqldb -d -p 3307:3306 -e MYSQL_ROOT_PASSWORD=password mysql
  - docker pull sath89/oracle-xe-11g
  - docker run --name orcldb -d -p 1521:1521 sath89/oracle-xe-11g
  - docker ps -a
  - docker exec -it orcldb "sqlplus"
  - system
  - oracle
  - create user test quota unlimited on system identified by test;
  - create table test.table2 (id integer, column1 varchar2(100), column2 number);
  - exit

install: "pip install -r requirements.txt"

script: nosetests

after_script:
  - docker rm -f mysqldb
  - docker rm -f orcldb