sudo: required

language: python

python:
  - "3.5"

services:
  - docker

before_install:
  - docker pull mysql:5.7
  - docker run --name mysql57 -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password mysql:5.7

install: "pip install -r requirements.txt"

script:
  - python -m unittest etlstat/extractor/test/testExtractor.py
  - python -m unittest etlstat/extractor/test/testPcaxis.py
  - python -m unittest etlstat/security/test/testPassword.py

after_script:
  - docker rm -f mysql57